# docker compose postgres instance
services:
  postgres:
    image: postgres:15.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: logs
    command: ["postgres", "-c", "log_statement=all"]
