services:
  postgres:
    image: postgres:15.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: logs
  log_ingest_api:
    build:
      context: .
      target: production
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/logs
      LOG_LEVEL: debug
    depends_on:
      - postgres
